from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from fastapi.testclient import TestClient

from collector.db import connect_db, ensure_schema, insert_story, insert_story_source, replace_story_key_points
from story_service.app import create_app


class TestStoryService(unittest.TestCase):
    def setUp(self) -> None:
        self.tmpdir = tempfile.TemporaryDirectory()
        self.db_path = Path(self.tmpdir.name) / "service.db"
        conn = connect_db(self.db_path)
        ensure_schema(conn)

        insert_story(
            conn,
            story_id="story_ok",
            topic_slug="world",
            headline="Global story headline",
            summary="x" * 360,
            published_at="2026-03-14T10:00:00+00:00",
            source_count=1,
            created_at="2026-03-14T10:10:00+00:00",
            status="publishable",
            publishability_reason=None,
            keypoints_generated_at="2026-03-14T10:11:00+00:00",
        )
        insert_story_source(
            conn,
            story_source_id="ss_ok",
            story_id="story_ok",
            source_name="Reuters",
            source_url="https://reuters.com/example",
            canonical_url="https://reuters.com/example",
            publisher_domain="reuters.com",
        )
        replace_story_key_points(
            conn,
            story_id="story_ok",
            key_points=["Point one", "Point two", "Point three", "Point four"],
            created_at="2026-03-14T10:11:00+00:00",
        )

        insert_story(
            conn,
            story_id="story_blocked",
            topic_slug="health",
            headline="Blocked story",
            summary="Blocked summary",
            published_at="2026-03-14T11:00:00+00:00",
            source_count=1,
            created_at="2026-03-14T11:01:00+00:00",
            status="not_publishable",
            publishability_reason="keypoints_invalid_count",
            keypoints_generated_at="2026-03-14T11:02:00+00:00",
        )
        insert_story_source(
            conn,
            story_source_id="ss_blocked",
            story_id="story_blocked",
            source_name="BBC",
            source_url="https://bbc.com/example",
            canonical_url="https://bbc.com/example",
            publisher_domain="bbc.com",
        )
        conn.commit()
        conn.close()

        self.client = TestClient(create_app(db_path=self.db_path))

    def tearDown(self) -> None:
        self.tmpdir.cleanup()

    def test_get_story_publishable_returns_contract(self) -> None:
        response = self.client.get("/stories/story_ok")
        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertEqual(payload["story_id"], "story_ok")
        self.assertEqual(payload["topic_slug"], "world")
        self.assertEqual(len(payload["key_points"]), 4)
        self.assertEqual(len(payload["sources"]), 1)
        self.assertFalse(payload["quiz_available"])
        self.assertFalse(payload["comment_enabled"])
        self.assertLessEqual(len(payload["summary"]), 320)

    def test_get_story_not_publishable_returns_410(self) -> None:
        response = self.client.get("/stories/story_blocked")
        self.assertEqual(response.status_code, 410)
        self.assertEqual(response.json()["detail"], "story_not_publishable")

    def test_get_story_missing_returns_404(self) -> None:
        response = self.client.get("/stories/not_found")
        self.assertEqual(response.status_code, 404)
        self.assertEqual(response.json()["detail"], "story_not_found")

    def test_get_story_page_respects_section_order_and_attribution(self) -> None:
        response = self.client.get("/stories/story_ok/page")
        self.assertEqual(response.status_code, 200)
        html = response.text

        markers = [
            'id="section-topic-badge"',
            'id="section-headline"',
            'id="section-snippet"',
            'id="section-key-points"',
            'id="section-attribution"',
            'id="section-verification-box"',
            'id="section-credits-teaser"',
        ]
        positions = [html.index(marker) for marker in markers]
        self.assertEqual(positions, sorted(positions))

        self.assertIn("Summary generated by Poli-News", html)
        self.assertIn('href="https://reuters.com/example"', html)
        self.assertLess(html.index('id="section-attribution"'), html.index('id="section-verification-box"'))

    def test_credits_teaser_auth_toggle(self) -> None:
        anon = self.client.get("/stories/story_ok/page")
        self.assertEqual(anon.status_code, 200)
        self.assertIn("Sign in to earn credits for reading", anon.text)

        auth = self.client.get("/stories/story_ok/page?auth=1&balance=77")
        self.assertEqual(auth.status_code, 200)
        self.assertIn("You have 77 credits", auth.text)


if __name__ == "__main__":
    unittest.main()

