from pathlib import Path

REQUEST_TIMEOUT_SECONDS = 8
MAX_RETRIES = 3
BACKOFF_SECONDS = (1, 3, 9)
USER_AGENT = "PoliNewsMVPFeedCollector/1.0"
STALE_THRESHOLD = 3
DEDUP_WINDOW_HOURS = 24
CANONICAL_RESOLVE_TIMEOUT_SECONDS = REQUEST_TIMEOUT_SECONDS
CANONICAL_RESOLVE_MAX_RETRIES = MAX_RETRIES
CANONICAL_RESOLVE_BACKOFF_SECONDS = BACKOFF_SECONDS

DEFAULT_FEEDS_CSV = Path("docs/mvp_offchain/specs/feed_registry_v1.csv")
DEFAULT_DB_PATH = Path("data/polinews.db")
DEFAULT_LOG_DIR = Path("logs")
DEFAULT_STATE_PATH = Path("data/stale_state.json")
